### ISSUE TITLE
Segfault on some PNG images

### ISSUE THREAD

**Issue by EXL** [codemeow/raBBit#1]
With this PNG image:

![Predator](http://rgho.st/7jM6SVRPz/image.png)

``` bash
$ raBBit -codp predator.png
```

```
<55bt full
>&"bt full\n"
>~"#0  0x00007ffff6fb462e in vfprintf () from /usr/lib/libc.so.6\n"
>~"No symbol table info available.\n"
>~"#1  0x00007ffff6fd72eb in vsprintf () from /usr/lib/libc.so.6\n"
>~"No symbol table info available.\n"
>~"#2  0x00007ffff6fbaed7 in sprintf () from /usr/lib/libc.so.6\n"
>~"No symbol table info available.\n"
>~"#3  0x000000000040230f in subprocesscenter () at ../../raBBit/processing/processor.c:216\n"
>~"        cols_s = \"transparent\\000\\226\\210\342\226\210\342\226\210\""
>~"\n"
>~"        cols = 0x7fffff005d72 <error: Cannot access memory at address 0x7fffff005d72>"
>~"\n"
>~"        same = RBB_FALSE"
>~"\n"
>~"        colstring = \"[color=transparent]\342\226\210\342\226\210[/color]\\000]\\000olor]\\000olor]\\000\\210[/color]\\000olor]\\000/color]\", '\\000' <repeats 4024 times>"
>~"\n"
>~"        cpixel = {alpha = 7 '\\a'"
>~", red = 61 '='"
>~", green = 61 '='"
>~", blue = 61 '='"
>~"}"
>~"\n"
>~"        opixel = {alpha = 187 '\\273'"
>~", red = 70 'F'"
>~", green = 70 'F'"
>~", blue = 70 'F'"
>~"}"
>~"\n"
>~"        used = RBB_TRUE"
>~"\n"
>~"        datastring = \"[color=#515151]\342\226\210\342\226\210[/color][color=#5a5a5a]\342\226\210\342\226\210[/color][color=#555555]\342\226\210\342\226\210[/color][color=#3d3d3d]\342\226\210\342\226\210[/color][color=#131313]\342\226\210\342\226\210[/color][color=#000000]\342\226\210\342\226\210\342\226\210\342\226\210\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#090909]\342\226\210\342\226\210[/color][color=#0a0a0a]\342\226\210\342\226\210[/color][color=#050505]\342\226\210\342\226\210[/color][color=#020202]\342\226\210\342\226\210[/color][color=#010101]\342\226\210\342\226\210[/color][color=transparent]\342\226\210\342\226\210[/color][color=transparent]\342\226\210\342\226\210[/color][color=#58504d]\342\226\210\342\226\210[/color][color=#625754]\342\226\210\342\226\210[/color][color=#695e5b]\342\226\210\342\226\210[/color][color=#6d615e]\342\226\210\342\226\210[/color][color=#746865]\342\226\210\342\226\210[/color][color=#776c69]\342\226\210\342\226\210[/color][color=#736965]\342\226\210\342\226\210[/color][color=#615555]\342\226\210\342\226\210[/color][color=#584d4d]\342\226\210\342\226\210[/color][color=#6a6262]\342\226\210\342\226\210[/color][color=#847b7b]\342\226\210\342\226\210[/color][color=#7a7373]\342\226\210\342\226\210[/color][color=#564f4f]\342\226\210\342\226\210[/color][color=#4d4745]\342\226\210\342\226\210[/color][color=#625c5a]\342\226\210\342\226\210[/color][color=#9e9a97]\342\226\210\342\226\210[/color][color=#b0aba9]\342\226\210\342\226\210[/color][color=#aca8a5]\342\226\210\342\226\210[/color][color=#b2adab]\342\226\210\342\226\210[/color][color=#a9a39e]\342\226\210\342\226\210[/color][color=#7e7873]\342\226\210\342\226\210[/color][color=#817b77]\342\226\210\342\226\210[/color][color=#87817d]\342\226\210\342\226\210[/color][color=#8d8785]\342\226\210\342\226\210[/color][color=#b2acaa]\342\226\210\342\226\210[/color][color=#bfb9b7]\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#beb9b8]\342\226\210\342\226\210[/color][color=#bfbab9]\342\226\210\342\226\210[/color][color=#c1bdbb]\342\226\210\342\226\210[/color][color=#c4bfbe]\342\226\210\342\226\210[/color][color=#c2bebf]\342\226\210\342\226\210\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#c4bfc0]\342\226\210\342\226\210[/color][color=#c5c0c1]\342\226\210\342\226\210[/color][color=#c6c1c2]\342\226\210\342\226\210[/color][color=#c7c2c4]\342\226\210\342\226\210[/color][color=#c8c4c5]\342\226\210\342\226\210[/color][color=#cbc6c7]\342\226\210\342\226\210[/color][color=#cdc8c9]\342\226\210\342\226\210[/color][color=#c7c2c4]\342\226\210\342\226\210[/color][color=#c0bbbd]\342\226\210\342\226\210[/color][color=#c2bebf]\342\226\210\342\226\210[/color][color=#c6c1c2]\342\226\210\342\226\210[/color][color=#c9c5c6]\342\226\210\342\226\210[/color][color=#ccc7c8]\342\226\210\342\226\210[/color][color=#cecccd]\342\226\210\342\226\210[/color][color=#d3d0d2]\342\226\210\342\226\210[/color][color=#d6d4d5]\342\226\210\342\226\210[/color][color=#dad7d9]\342\226\210\342\226\210[/color][color=#dedcdd]\342\226\210\342\226\210[/color][color=#e1dedf]\342\226\210\342\226\210[/color][color=#e2dfe1]\342\226\210\342\226\210\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#dedcdd]\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#dad7d9]\342\226\210\342\226\210[/color][color=#d7d5d6]\342\226\210\342\226\210[/color][color=#d4d2d3]\342\226\210\342\226\210[/color][color=#d0cecf]\342\226\210\342\226\210[/color][color=#cdcbcc]\342\226\210\342\226\210[/color][color=#cdc8c9]\342\226\210\342\226\210[/color][color=#c9c5c6]\342\226\210\342\226\210[/color][color=#c7c2c4]\342\226\210\342\226\210[/color][color=#c4bfc0]\342\226\210\342\226\210[/color][color=#c0bbbd]\342\226\210\342\226\210[/color][color=#bdb8b9]\342\226\210\342\226\210[/color][color=#b8b3b4]\342\226\210\342\226\210[/color][color=#b6b1b2]\342\226\210\342\226\210[/color][color=#b1acad]\342\226\210\342\226\210[/color][color=#ada9aa]\342\226\210\342\226\210[/color][color=#aaa5a6]\342\226\210\342\226\210[/color][color=#a6a2a3]\342\226\210\342\226\210[/color][color=#a49fa1]\342\226\210\342\226\210[/color][color=#a29d9e]\342\226\210\342\226\210[/color][color=#9e9a9b]\342\226\210\342\226\210[/color][color=#9c9798]\342\226\210\342\226\210[/color][color=#9c9595]\342\226\210\342\226\210[/color][color=#9a9393]\342\226\210\342\226\210[/color][color=#989191]\342\226\210\342\226\210[/color][color=#979090]\342\226\210\342\226\210[/color][color=#958e8e]\342\226\210\342\226\210[/color][color=#968f8f]\342\226\210\342\226\210[/color][color=#958e8e]\342\226\210\342\226\210[/color][color=#938c8c]\342\226\210\342\226\210[/color][color=#918b8d]\342\226\210\342\226\210[/color][color=#8f888b]\342\226\210\342\226\210[/color][color=#8e8789]\342\226\210\342\226\210[/color][color=#8c8587]\342\226\210\342\226\210[/color][color=#898285]\342\226\210\342\226\210[/color][color=#857e80]\342\226\210\342\226\210[/color][color=#7f7a7b]\342\226\210\342\226\210[/color][color=#767374]\342\226\210\342\226\210[/color][color=#706a6f]\342\226\210\342\226\210[/color][color=#6b656a]\342\226\210\342\226\210[/color][color=#666165]\342\226\210\342\226\210[/color][color=#625c61]\342\226\210\342\226\210[/color][color=#5c565b]\342\226\210\342\226\210[/color][color=#504a4f]\342\226\210\342\226\210[/color][color=#454246]\342\226\210\342\226\210[/color][color=#3e3b3f]\342\226\210\342\226\210[/color][color=#3e393a]\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#3b393a]\342\226\210\342\226\210[/color][color=#3a3839]\342\226\210\342\226\210[/color][color=#3d3a3b]\342\226\210\342\226\210[/color][color=#4a4849]\342\226\210\342\226\210[/color][color=#534e4f]\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#575351]\342\226\210\342\226\210[/color][color=#5a5353]\342\226\210\342\226\210[/color][color=#5c5453]\342\226\210\342\226\210[/color][color=#635b5a]\342\226\210\342\226\210[/color][color=#645c5b]\342\226\210\342\226\210[/color][color=#5c5453]\342\226\210\342\226\210[/color][color=#5b5454]\342\226\210\342\226\210[/color][color=#615a5a]\342\226\210\342\226\210[/color][color=#665e5e]\342\226\210\342\226\210[/color][color=#695d5e]\342\226\210\342\226\210[/color][color=#6d6262]\342\226\210\342\226\210[/color][color=transparent]\342\226\210\342\226\210[/color][color=transparent]\342\226\210\342\226\210[/color][color=#060305]\342\226\210\342\226\210[/color][color=#010101]\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#000000]\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#020202]\342\226\210\342\226\210[/color][color=#282828]\342\226\210\342\226\210[/color][color=#4a4a4a]\342\226\210\342\226\210[/color][color=#585858]\342\226\210\342\226\210\342\226\210\342\226\210[/color][color=#4f4f4f]\342\226\210\342\226\210[/color][color=transparent]\", <incomplete sequence \\342>"
>~"\n"
>~"        x = 201"
>~"\n"
>~"        y = 60"
>~"\n"
>~"        xlimit = 0x6236e0\n"
>~"#4  0x0000000000402845 in processdata () at ../../raBBit/processing/processor.c:320\n"
>~"        _res_ = RBB_ERRORS_SUCCESS"
>~"\n"
>~"#5  0x0000000000400f3d in main (argc=3, argv=0x7fffffffe328) at ../../raBBit/main.c:33\n"
>~"        _res_ = 4294959904"
>~"\n"
>55^done
```

If I increase the size of the string buffer from 

``` c
char datastring[4096];
```

to

``` c
char datastring[8192];
```

segfault isn't happens.

Maybe you should limit the height and width of PNG images until 256x256? 
Or increase size of string buffer?

**Comment by codemeow** [comment]
I wasn't expecting the images to be too big, because since it's forum tool the screen limits are actually very small.

Here, I removed static strings and made pessimistic dynamic allocation. Could you, please, retest it now?

**Comment by EXL** [comment]
> Here, I removed static strings and made pessimistic dynamic allocation. Could you, please, retest it now?

Cool, now works with PNG of different sizes.
Thanks! Please close the issue.
